config/routes.rb
Rails.application.routes.draw do
  resources :another_examples
  devise_for :users
  resources :users
  resources :examples

  root 'examples#index'

end

app/models/another_example.rb
class AnotherExample < ActiveRecord::Base
  include Authority::Abilities
end

app/models/example.rb
class Example < ActiveRecord::Base
  include Authority::Abilities
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
  include Authority::UserAbilities
end

app/controllers/another_examples_controller.rb
class AnotherExamplesController < ApplicationController
  before_action :set_another_example, only: [:show, :edit, :update, :destroy]
  authorize_actions_for AnotherExample
  # authority_actions :breed => 'create', :vaporize => 'delete'

  # GET /another_examples
  # GET /another_examples.json
  def index
    @another_examples = AnotherExample.all
  end

  # GET /another_examples/1
  # GET /another_examples/1.json
  def show
  end

  # GET /another_examples/new
  def new
    @another_example = AnotherExample.new
  end

  # GET /another_examples/1/edit
  def edit
  end

  # POST /another_examples
  # POST /another_examples.json
  def create
    @another_example = AnotherExample.new(another_example_params)

    respond_to do |format|
      if @another_example.save
        format.html { redirect_to @another_example, notice: 'Another example was successfully created.' }
        format.json { render :show, status: :created, location: @another_example }
      else
        format.html { render :new }
        format.json { render json: @another_example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /another_examples/1
  # PATCH/PUT /another_examples/1.json
  def update
    respond_to do |format|
      if @another_example.update(another_example_params)
        format.html { redirect_to @another_example, notice: 'Another example was successfully updated.' }
        format.json { render :show, status: :ok, location: @another_example }
      else
        format.html { render :edit }
        format.json { render json: @another_example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /another_examples/1
  # DELETE /another_examples/1.json
  def destroy
    @another_example.destroy
    respond_to do |format|
      format.html { redirect_to another_examples_url, notice: 'Another example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_another_example
      @another_example = AnotherExample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def another_example_params
      params.require(:another_example).permit(:title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
    authorize_action_for(@example)
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/another_examples/_form.html.erb
<%= form_for(@another_example) do |f| %>
  <% if @another_example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@another_example.errors.count, "error") %> prohibited this another_example from being saved:</h2>

      <ul>
      <% @another_example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/another_examples/edit.html.erb
<h1>Editing Another Example</h1>

<%= render 'form' %>

<%= link_to 'Show', @another_example %> |
<%= link_to 'Back', another_examples_path %>

app/views/another_examples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Another Examples</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @another_examples.each do |another_example| %>
      <tr>
        <td><%= another_example.title %></td>
        <td><%= link_to 'Show', another_example %></td>
        <td><%= link_to 'Edit', edit_another_example_path(another_example) %></td>
        <td><%= link_to 'Destroy', another_example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Another example', new_another_example_path %>

app/views/another_examples/new.html.erb
<h1>New Another Example</h1>

<%= render 'form' %>

<%= link_to 'Back', another_examples_path %>

app/views/another_examples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @another_example.title %>
</p>

<%= link_to 'Edit', edit_another_example_path(@another_example) %> |
<%= link_to 'Back', another_examples_path %>

app/views/examples/_form.html.erb
<%= form_for(@example) do |f| %>
  <% if @example.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
      <% @example.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form' %>

<%= link_to 'Show', @example %> |
<%= link_to 'Back', examples_path %>

app/views/examples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Examples</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.title %></td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', edit_example_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } if current_user.can_delete?(example) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>

<%#= 'View Something' if current_user.can?(:view_something) %>

app/views/examples/new.html.erb
<h1>New Example</h1>

<%= render 'form' %>

<%= link_to 'Back', examples_path %>

app/views/examples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @example.title %>
</p>

<%= link_to 'Edit', edit_example_path(@example) %> |
<%= link_to 'Back', examples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- <p class="notice"><%= notice %></p> -->
  <!-- <p class="alert"><%= alert %></p> -->
  <br/>
  <title>Authoritay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>